
export const GEOJSON_URL = "https://ia601703.us.archive.org/6/items/prov_ma_202601/prov_ma.txt";

export const REGIONS_LIST = [
  "Casablanca-Settat",
  "Marrakech-Safi",
  "Rabat-Salé-Kénitra",
  "Fès-Meknès",
  "Souss-Massa",
  "Béni Mellal-Khénifra",
  "Oriental",
  "Drâa-Tafilalet",
  "Guelmim-Oued Noun",
  "Laâyoune-Sakia El Hamra",
  "Dakhla-Oued Ed-Dahab",
  "Tanger-Tétouan-Al Hoceïma"
];

export const PROVINCE_TO_REGION: Record<string, string> = {
  "OUAD EDDAHAB": "Dakhla-Oued Ed-Dahab",
  "AOUSSERD": "Dakhla-Oued Ed-Dahab",
  "LAAYOUNE": "Laâyoune-Sakia El Hamra",
  "BOUJDOUR": "Laâyoune-Sakia El Hamra",
  "ESSMARA": "Laâyoune-Sakia El Hamra",
  "TRAFAYA": "Laâyoune-Sakia El Hamra",
  "GUELMIM": "Guelmim-Oued Noun",
  "ASSA - ZAG": "Guelmim-Oued Noun",
  "SIDI IFNI": "Guelmim-Oued Noun",
  "TAN - TAN": "Guelmim-Oued Noun",
  "AGADIR IDA OU TANANE": "Souss-Massa",
  "INEZEGANE AIT MELLOUL": "Souss-Massa",
  "CHTOUKA AIT BAHA": "Souss-Massa",
  "TAROUDANNT": "Souss-Massa",
  "TIZNIT": "Souss-Massa",
  "TATA": "Souss-Massa",
  "TINGHIR": "Drâa-Tafilalet",
  "OURZAZTE": "Drâa-Tafilalet",
  "ZAGORA": "Drâa-Tafilalet",
  "MIDELT": "Drâa-Tafilalet",
  "ERRACHIDIA": "Drâa-Tafilalet",
  "MARRAKECH": "Marrakech-Safi",
  "AL HAOUZ": "Marrakech-Safi",
  "CHICHAOUA": "Marrakech-Safi",
  "EL KELAA DES SRAGHNA": "Marrakech-Safi",
  "REHAMNA": "Marrakech-Safi",
  "YOUSSOUFIA": "Marrakech-Safi",
  "SAFI": "Marrakech-Safi",
  "ESSAOUIRA": "Marrakech-Safi",
  "BENI MELLAL": "Béni Mellal-Khénifra",
  "AZILAL": "Béni Mellal-Khénifra",
  "FQUIH BEN SALAH": "Béni Mellal-Khénifra",
  "KHENIFRA": "Béni Mellal-Khénifra",
  "KHOURIBGA": "Béni Mellal-Khénifra",
  "CASABLANCA": "Casablanca-Settat",
  "MOHAMMEDIA": "Casablanca-Settat",
  "MÉDIOUNA": "Casablanca-Settat",
  "NOUACER": "Casablanca-Settat",
  "BERCHID": "Casablanca-Settat",
  "BEN SLIMANE": "Casablanca-Settat",
  "SETTAT": "Casablanca-Settat",
  "SIDI BENNOUR": "Casablanca-Settat",
  "EL JADIDA": "Casablanca-Settat",
  "RABAT": "Rabat-Salé-Kénitra",
  "SALÉ": "Rabat-Salé-Kénitra",
  "SKHIRATE- TEMARA": "Rabat-Salé-Kénitra",
  "KÉNITRA": "Rabat-Salé-Kénitra",
  "KHEMISSET": "Rabat-Salé-Kénitra",
  "SIDI KACEM": "Rabat-Salé-Kénitra",
  "SIDI SLIMANE": "Rabat-Salé-Kénitra",
  "FÈS": "Fès-Meknès",
  "MEKNES": "Fès-Meknès",
  "EL HAJEB": "Fès-Meknès",
  "SEFROU": "Fès-Meknès",
  "IFRANE": "Fès-Meknès",
  "BOULEMANE": "Fès-Meknès",
  "TAZA": "Fès-Meknès",
  "TAOUNATE": "Fès-Meknès",
  "MOULAY YACOUB": "Fès-Meknès",
  "OUJDA - ANGAD": "Oriental",
  "NADOR": "Oriental",
  "BERKANE": "Oriental",
  "TAOURIRT": "Oriental",
  "JRADA": "Oriental",
  "FIGUIG": "Oriental",
  "GUERSSIF": "Oriental",
  "DRIOUCH": "Oriental",
  "TANGER - ASILAH": "Tanger-Tétouan-Al Hoceïma",
  "M'DIQ-FNIDEQ": "Tanger-Tétouan-Al Hoceïma",
  "TETOUAN": "Tanger-Tétouan-Al Hoceïma",
  "LARACHE": "Tanger-Tétouan-Al Hoceïma",
  "AL HOUCEIMA": "Tanger-Tétouan-Al Hoceïma",
  "CHEFCHAOUEN": "Tanger-Tétouan-Al Hoceïma",
  "OUAZZANE": "Tanger-Tétouan-Al Hoceïma",
  "EL FAHS - ANGRA": "Tanger-Tétouan-Al Hoceïma"
};

export const DOWNLOAD_LINKS: Record<string, string> = {
  "AGADIR IDA OU TANANE": "https://drive.google.com/file/d/1UWDokzDiJuNO6_vqc590B87iEF9_IcTK/view",
  "AL HOUCEIMA": "https://drive.google.com/file/d/1YfXPI41zaqDRkX0LVMtdQyGlzD65ZWi-",
  "TANGER - ASILAH": "https://drive.google.com/file/d/1YlidcDUw3SPD7FeNnignFL7TesbRaxp3",
  "NADOR": "https://drive.google.com/file/d/1wanlzg6Fa9G_Wi6818LwpNn1kNTJntJm",
  "SEFROU": "https://drive.google.com/file/d/1ppx8GAqzlTGkrfG9aqX3GDkSt2m6tpJg",
  "OURZAZTE": "https://drive.google.com/file/d/1pUAIzQBujnLogFnYkx6Tyjj_bn7nS_7N",
  "KHENIFRA": "https://drive.google.com/file/d/1ROc0iqfuE_koHagIEjtORQA9jyyhrBsD",
  "MIDELT": "https://drive.google.com/file/d/1XBBoFWEYrWED6bpn0Cjv_gKOEaLqgacF",
  "LAAYOUNE": "https://drive.google.com/file/d/1skAk7DnHMT8KbdckQueH7Vt8OB1RcwUy",
  "TAZA": "https://drive.google.com/file/d/1t2o1j6mwy2BW9mkfCVzOFTS-KQhr3w4H",
  "TAOURIRT": "https://drive.google.com/file/d/14YVjpHq26bcoIjSO-VoKTVNhgzxBQdNY",
  "KHEMISSET": "https://drive.google.com/file/d/1d5IUnW_2pAhg64VUqCmf3dk8fr9fG6d_",
  "FQUIH BEN SALAH": "https://drive.google.com/file/d/1rjAx7oPAKQ00teooftXITob8yT-Qpruf",
  "BENI MELLAL": "https://drive.google.com/file/d/1anC3cMqAJrhrjhZ21NPK8CnMuJcWLHOu",
  "BERKANE": "https://drive.google.com/file/d/1sv-PSyXqi5uSg-ddUoUBJ9rh2096_OPW",
  "GUELMIM": "https://drive.google.com/file/d/1nXiPzn8Q-wXaJvoy7m7gEBZNzlY-WKc1",
  "GUERSSIF": "https://drive.google.com/file/d/1X-Z6WjtJUp7Zj-ggm9PvWJZiE_DlP0AZ",
  "MEKNES": "https://drive.google.com/file/d/1a8GSI4_0a6L1hgkaAO0LrJBZ4X0fa6K4",
  "EL HAJEB": "https://drive.google.com/file/d/1BS7zD6tcsHBTIc8_GRnPWHN06veAOavG",
  "CHTOUKA AIT BAHA": "https://drive.google.com/file/d/16H78YAucHZ2dmHBlQoEYAZjyTOeRKxrn",
  "SIDI SLIMANE": "https://drive.google.com/file/d/1Zg_ZHhCCm11UG740ntFhOojgK3Qn6ZZF",
  "ESSAOUIRA": "https://drive.google.com/file/d/1L_t0wJAVCE9ARPZqIj0oO0zs5WvGz-Tr",
  "ERRACHIDIA": "https://drive.google.com/file/d/1CQUSWjOngEjJ0wqb5KCyYZM6IwyvN5bN",
  "TIZNIT": "https://drive.google.com/file/d/1fhYvVKrfxseEfJYmFjNQIzxQaglz825M",
  "OUAD EDDAHAB": "https://drive.google.com/file/d/1W8TCjsJgGSjER0IZ8-oAd6YYIMAZzmul",
  "BERCHID": "https://drive.google.com/file/d/1urqgs3lWp_6bKJkded0vET9UI5rS2brY",
  "SKHIRATE- TEMARA": "https://drive.google.com/file/d/106K0yigp55ZDAGNQY_XVVY5WmZ-bAEJH",
  "TAROUDANNT": "https://drive.google.com/file/d/1xkm_jDhqofnXlYJwMFtXJvnotQNplNSw",
  "LARACHE": "https://drive.google.com/file/d/1BVFiiO3aRAGQRAOws-wZyeZoMBfveQS2",
  "RABAT": "https://drive.google.com/file/d/13QhQIUO1ItLQi133fQ8p2yxHsEdw0oVn",
  "INEZEGANE AIT MELLOUL": "https://drive.google.com/file/d/1yyd-GQF5BVfF4SrYlwGPEkr7ucxYhiql",
  "KHOURIBGA": "https://drive.google.com/file/d/1V-nlu6qBQIBwhCqT-yV7pHOJK_8z3AyZ",
  "FÈS": "https://drive.google.com/file/d/1a6QUwgao4okjcyR1V_Hz3BAWZVeo-MS5",
  "SIDI KACEM": "https://drive.google.com/file/d/1-exZqMZPQ62H4X3PH5iFoiic1XzSvDXv",
  "SIDI BENNOUR": "https://drive.google.com/file/d/1eLfmImakIX_B2h0KNBCYrx3LF8H0Mm--",
  "IFRANE": "https://drive.google.com/file/d/1c1w2yGvR3cahFsSbCSt7kD2maEkedhr7",
  "KÉNITRA": "https://drive.google.com/file/d/1fhdAWLXrNEcGR42QRX6b8q9zh3BfP2Ry",
  "SETTAT": "https://drive.google.com/file/d/1Rm37o7-ybmDhlLAJWg2-LUVoH0ZxqIx7",
  "TETOUAN": "https://drive.google.com/file/d/1ykxVLBOxAwNM5H61uMDdh2b05v5ftgku",
  "MOHAMMEDIA": "https://drive.google.com/file/d/1Nz8_GFQNNw_4FEgXeTHTcubYd1oxMKyt",
  "NOUACER": "https://drive.google.com/file/d/1ZTRHOun341z907E2ncXxrxjJgDd--E83",
  "CASABLANCA": "https://drive.google.com/file/d/19dK56HuNRDSxyaXPbBGA7bpaZkEo5bIq",
  "AZILAL": "https://drive.google.com/file/d/1yf752JHPOL8o8ol8bZv3_orPaqIpD60t",
  "BOULEMANE": "https://drive.google.com/file/d/1MO94Ql8RAyZaRSVW6R5uhA5wlvaA3q1L",
  "TAOUNATE": "https://drive.google.com/file/d/1nTYogtuaLXvMO6LGNkplVDIB8AGKsNrl"
};
